# clustering.py

import pickle
import numpy as np
import matplotlib
# Force matplotlib to use the non-interactive 'Agg' backend 
# to ensure server-side PNG rendering works seamlessly without a display server
matplotlib.use("Agg")
import matplotlib.pyplot as plt
#import matplotlib.colormaps

from sklearn.cluster import KMeans, MiniBatchKMeans
from sklearn.metrics import silhouette_score, silhouette_samples
from sklearn.decomposition import TruncatedSVD
from sklearn.preprocessing import Normalizer
from sklearn.pipeline import make_pipeline
from sklearn.manifold import TSNE

import os
# Establish the target results directory infrastructure if not already present
os.makedirs("results", exist_ok=True)


# =====================================================
# LOAD DATA
# =====================================================

print("Loading data...")

# Ingest the programmatic text train arrays generated by balance_topics.py
X_train = pickle.load(open("data/processed/X_train.pkl", "rb"))
y_train = pickle.load(open("data/processed/y_train.pkl", "rb"))

print(f"X_train shape : {X_train.shape}")
print(f"y_train shape : {y_train.shape}")


# =====================================================
# DIMENSIONALITY REDUCTION
# Raised from 100 → 200 components for better coverage.
# 100 components only explained ~17% variance which is
# too low — clusters are indistinguishable in that space.
# =====================================================

print("\nReducing dimensions with LSA (TruncatedSVD)...")

# Latent Semantic Analysis (LSA) pipeline utilizing singular value decomposition (SVD).
# Essential for sparse, high-dimensional text matrices where standard PCA fails.
svd        = TruncatedSVD(n_components=200, random_state=42)
# Apply L2 normalization to map document coordinates onto a unit hypersphere,
# ensuring Euclidean distance calculations inside KMeans function as cosine similarity.
normalizer = Normalizer(copy=False)
lsa_pipe   = make_pipeline(svd, normalizer)

X_lsa = lsa_pipe.fit_transform(X_train)

# Calculate the cumulative variance explained by the 200 semantic coordinates
explained = svd.explained_variance_ratio_.sum()
print(f"Explained variance (200 components): {explained:.2%}")


# =====================================================
# ELBOW METHOD
# =====================================================

print("\nRunning elbow method (k = 2 to 10)...")

K_RANGE  = range(2, 11)
inertias = []

# Iteratively track the within-cluster Sum of Squared Errors (SSE) across cluster spaces
for k in K_RANGE:
    km = KMeans(n_clusters=k, random_state=42, n_init=10, max_iter=300)
    km.fit(X_lsa)
    inertias.append(km.inertia_) # Inertia captures total squared distance to closest centroid
    print(f"  k={k}  inertia={km.inertia_:,.0f}")

# --- plot elbow curve ---
fig, ax = plt.subplots(figsize=(8, 4))
ax.plot(list(K_RANGE), inertias, marker="o", linewidth=2, color="#185FA5")
ax.set_xlabel("Number of clusters (k)")
ax.set_ylabel("Inertia (within-cluster SSE)")
ax.set_title("Elbow Method — KMeans Inertia")
ax.set_xticks(list(K_RANGE))
ax.grid(axis="y", linestyle="--", alpha=0.4)
plt.tight_layout()
plt.savefig("results/elbow_plot.png", dpi=150)
plt.close()
print("Saved: results/elbow_plot.png")


# =====================================================
# SILHOUETTE SCORES
# =====================================================

print("\nComputing silhouette scores...")

silhouette_scores = {}

# Quantify clustering quality by measuring individual sample separation and cohesion boundaries
for k in K_RANGE:
    km     = KMeans(n_clusters=k, random_state=42, n_init=10, max_iter=300)
    labels = km.fit_predict(X_lsa)
    # Downsample sample size to 5,000 to drastically optimize silhouette runtime overhead
    score  = silhouette_score(X_lsa, labels, sample_size=5000, random_state=42)
    silhouette_scores[k] = score
    print(f"  k={k}  silhouette={score:.4f}")

# Isolate the cluster value that maximizes text density structure parameters
best_k     = max(silhouette_scores, key=silhouette_scores.get)
best_score = silhouette_scores[best_k]
print(f"\nBest k by silhouette: k={best_k}  score={best_score:.4f}")

# --- plot silhouette leaderboard ---
fig, ax = plt.subplots(figsize=(8, 4))
ks     = list(silhouette_scores.keys())
scores = list(silhouette_scores.values())
# Highlight the mathematically optimal cluster configuration in solid blue
colors = ["#185FA5" if k == best_k else "#B5D4F4" for k in ks]
bars   = ax.bar(ks, scores, color=colors, edgecolor="white", width=0.6)
ax.set_xlabel("Number of clusters (k)")
ax.set_ylabel("Silhouette score")
ax.set_title("Silhouette Score by k")
ax.set_xticks(ks)
ax.set_ylim(0, max(scores) * 1.3)
# Overlay exact evaluation scores explicitly onto text labels
for bar, score in zip(bars, scores):
    ax.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 0.001,
        f"{score:.3f}",
        ha="center", va="bottom", fontsize=9
    )
plt.tight_layout()
plt.savefig("results/silhouette_scores_by_k.png", dpi=150)
plt.close()
print("Saved: results/silhouette_scores_by_k.png")


# =====================================================
# FINAL KMEANS — best k
# =====================================================

print(f"\nFitting final KMeans with k={best_k}...")

# Execute fully converged mathematical training loop on the mathematically optimized best k
best_km     = KMeans(n_clusters=best_k, random_state=42, n_init=20, max_iter=500)
best_labels = best_km.fit_predict(X_lsa)

print("Fitting KMeans k=2 (compare vs true labels)...")
# Force a 2-cluster baseline environment to directly validate target class sorting behaviors
km2        = KMeans(n_clusters=2, random_state=42, n_init=20, max_iter=500)
km2_labels = km2.fit_predict(X_lsa)

score_k2 = silhouette_score(X_lsa, km2_labels, sample_size=5000, random_state=42)
print(f"  k=2 silhouette: {score_k2:.4f}")


# =====================================================
# SILHOUETTE DETAIL PLOT — best k
# FIX: matplotlib.colormaps instead of deprecated cm.get_cmap
# =====================================================

print(f"\nBuilding silhouette plot for k={best_k}...")

# Sample records to optimize execution bounds while holding seed integrity constants
sample_idx  = np.random.RandomState(42).choice(len(X_lsa), size=min(5000, len(X_lsa)), replace=False)
X_sample    = X_lsa[sample_idx]
labels_samp = best_labels[sample_idx]

sample_silhouette_vals = silhouette_samples(X_sample, labels_samp)

fig, ax = plt.subplots(figsize=(9, 5))
y_lower = 10

# FIX: use matplotlib.colormaps["tab10"] — compatible with matplotlib 3.7+ configurations
cmap = matplotlib.colormaps["tab10"]

# Plot the sorted silhouette profiles for each discrete cluster block
for i in range(best_k):
    cluster_vals = np.sort(sample_silhouette_vals[labels_samp == i])
    size_i  = len(cluster_vals)
    y_upper = y_lower + size_i
    color   = cmap(i / best_k)
    ax.fill_betweenx(
        np.arange(y_lower, y_upper),
        0, cluster_vals,
        facecolor=color, edgecolor=color, alpha=0.7
    )
    ax.text(-0.02, y_lower + size_i / 2, str(i), fontsize=9)
    y_lower = y_upper + 10

avg_score = silhouette_score(X_sample, labels_samp)
# Draw the vertical mean index marker to evaluate cluster thicknesses and structural drops
ax.axvline(x=avg_score, color="red", linestyle="--",
           linewidth=1.2, label=f"Mean = {avg_score:.3f}")
ax.set_xlabel("Silhouette coefficient")
ax.set_ylabel("Cluster")
ax.set_title(f"Silhouette Plot — k={best_k}")
ax.legend(fontsize=9)
plt.tight_layout()
plt.savefig("results/silhouette_plot_best_k.png", dpi=150)
plt.close()
print("Saved: results/silhouette_plot_best_k.png")


# =====================================================
# t-SNE VISUALIZATION
# FIX: n_iter → max_iter  (renamed in sklearn 1.2+)
# Using 3000 sample points for reasonable speed
# =====================================================

print("\nRunning t-SNE on 3000 sample points...")

TSNE_N      = 3000
tsne_idx    = np.random.RandomState(0).choice(len(X_lsa), size=TSNE_N, replace=False)
X_tsne_in   = X_lsa[tsne_idx]
labels_tsne = best_labels[tsne_idx]
true_tsne   = np.array(y_train)[tsne_idx]

# t-distributed Stochastic Neighbor Embedding maps high-dimensional clouds into a 2D plane
tsne = TSNE(
    n_components=2,
    perplexity=40,            # Bounds local vs global structural emphasis balances
    max_iter=1000,            # FIX: was n_iter — renamed in sklearn 1.2+ parameters
    random_state=42,
    init="pca",               # PCA initialization preserves global consistency over random mappings
    learning_rate="auto"
)

X_2d = tsne.fit_transform(X_tsne_in)
print("t-SNE done.")

# Plot 1: colored by cluster | Plot 2: colored by true label
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Subplot 1: Map the structural shapes of unsupervised clusters
sc1 = axes[0].scatter(
    X_2d[:, 0], X_2d[:, 1],
    c=labels_tsne, cmap="tab10", s=5, alpha=0.6
)
axes[0].set_title(f"t-SNE — KMeans clusters (k={best_k})")
axes[0].set_xlabel("t-SNE 1")
axes[0].set_ylabel("t-SNE 2")
plt.colorbar(sc1, ax=axes[0], label="Cluster")

# Subplot 2: Overlap true target markers to explicitly visualize class boundaries
sc2 = axes[1].scatter(
    X_2d[:, 0], X_2d[:, 1],
    c=true_tsne, cmap="coolwarm", s=5, alpha=0.6
)
axes[1].set_title("t-SNE — True labels (0=Fake, 1=Real)")
axes[1].set_xlabel("t-SNE 1")
axes[1].set_ylabel("t-SNE 2")
plt.colorbar(sc2, ax=axes[1], label="True label")

plt.tight_layout()
plt.savefig("results/tsne_clusters.png", dpi=150)
plt.close()
print("Saved: results/tsne_clusters.png")


# =====================================================
# CLUSTER SIZE DISTRIBUTION
# =====================================================

print("\nCluster size distribution:")
unique, counts = np.unique(best_labels, return_counts=True)
for cid, cnt in zip(unique, counts):
    pct = cnt / len(best_labels) * 100
    print(f"  Cluster {cid}: {cnt:,} samples ({pct:.1f}%)")

# --- plot cluster distribution frequency ---
fig, ax = plt.subplots(figsize=(8, 4))
ax.bar(unique, counts, color="#185FA5", edgecolor="white", width=0.6)
ax.set_xlabel("Cluster ID")
ax.set_ylabel("Number of samples")
ax.set_title(f"Cluster size distribution (k={best_k})")
ax.set_xticks(unique)
for cid, cnt in zip(unique, counts):
    ax.text(cid, cnt + 80, f"{cnt:,}", ha="center", fontsize=9)
plt.tight_layout()
plt.savefig("results/cluster_sizes.png", dpi=150)
plt.close()
print("Saved: results/cluster_sizes.png")


# =====================================================
# k=2 ALIGNMENT vs TRUE LABELS
# =====================================================

print("\n--- k=2 cluster vs true label alignment ---")
y_arr = np.array(y_train)

# Analyze the exact target composition of the forced binary cluster spaces
for c in [0, 1]:
    mask      = km2_labels == c
    true_in_c = y_arr[mask]
    n_fake    = (true_in_c == 0).sum()
    n_real    = (true_in_c == 1).sum()
    dominant  = "Fake" if n_fake > n_real else "Real"
    print(
        f"  Cluster {c}: {mask.sum():,} samples | "
        f"fake={n_fake:,} ({n_fake / mask.sum():.1%}) | "
        f"real={n_real:,} ({n_real / mask.sum():.1%}) → mostly {dominant}"
    )


# =====================================================
# SAVE ARTIFACTS
# =====================================================

# Serialize output array configurations for report appendices and web dashboard ingestion
pickle.dump(best_labels, open("data/processed/cluster_labels.pkl", "wb"))
pickle.dump(km2_labels,  open("data/processed/cluster_labels_k2.pkl", "wb"))
pickle.dump(best_km,     open("models/kmeans_best.pkl", "wb"))

print(f"\n✅ Clustering complete")
print(f"   Best k         : {best_k}")
print(f"   Best silhouette: {best_score:.4f}")
print("\nArtifacts saved:")
print("   data/processed/cluster_labels.pkl")
print("   data/processed/cluster_labels_k2.pkl")
print("   models/kmeans_best.pkl")
print("\nPlots saved:")
for f in ["elbow_plot", "silhouette_scores_by_k", "silhouette_plot_best_k",
          "tsne_clusters", "cluster_sizes"]:
    print(f"   results/{f}.png")