# evaluate.py

import pickle
import numpy as np
import pandas as pd
import matplotlib
# Force matplotlib to use the non-interactive 'Agg' backend 
# to ensure server-side PNG rendering works seamlessly without a display server
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import seaborn as sns

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix,
    classification_report, roc_curve, precision_recall_curve,
    average_precision_score, matthews_corrcoef,
    ConfusionMatrixDisplay
)

import os
# Establish the target results directory infrastructure if not already present
os.makedirs("results", exist_ok=True)


# =====================================================
# LOAD TEST DATA
# =====================================================

print("Loading test data...")

# Ingest high-integrity sparse arrays and class partitions generated by balance_topics.py
X_test  = pickle.load(open("data/processed/X_test.pkl",  "rb"))
y_test  = pickle.load(open("data/processed/y_test.pkl",  "rb"))
X_train = pickle.load(open("data/processed/X_train.pkl", "rb"))
y_train = pickle.load(open("data/processed/y_train.pkl", "rb"))

print(f"Test  samples : {X_test.shape[0]:,}")
print(f"Train samples : {X_train.shape[0]:,}")


# =====================================================
# MODEL REGISTRY
# Explicit map connecting algorithm name keys directly to serialized model paths
# =====================================================

MODEL_PATHS = {
    "Logistic Regression"       : "models/logistic_regression.pkl",
    "Naive Bayes"               : "models/naive_bayes.pkl",
    "SVM"                       : "models/svm.pkl",
    "Random Forest"             : "models/random_forest.pkl",
    "Tuned Logistic Regression" : "models/logistic_regression_tuned.pkl",
    "Tuned SVM"                 : "models/svm_tuned.pkl",
    "Tuned Random Forest"       : "models/random_forest_tuned.pkl",
}

# =====================================================
# HELPERS
# =====================================================

def get_scores(model, X):
    """
    Return probability/decision scores for ROC/PR curves.
    Handles continuous decision space tracking variations across model types.
    """
    try:
        # Probabilistic classifiers output continuous classification ratios
        if hasattr(model, "predict_proba"):
            return model.predict_proba(X)[:, 1]
        # Hyper-plane margin boundaries classifiers output continuous distance floats
        else:
            return model.decision_function(X)
    except Exception:
        return None


def compute_all_metrics(model, X, y_true, split="TEST"):
    """Full metric set for one model on one split."""
    preds  = model.predict(X)
    scores = get_scores(model, X)

    # Compute macro global evaluation summary parameters
    acc   = accuracy_score(y_true, preds)
    prec  = precision_score(y_true, preds, zero_division=0)
    rec   = recall_score(y_true, preds, zero_division=0)
    f1    = f1_score(y_true, preds, zero_division=0)
    # MCC serves as a balanced evaluation summary tracking all 4 quadrants of the confusion matrix symmetrically
    mcc   = matthews_corrcoef(y_true, preds)

    # Compute un-averaged per-class precision / recall / f1 vectors
    prec_cls = precision_score(y_true, preds, average=None, zero_division=0)
    rec_cls  = recall_score(y_true, preds, average=None, zero_division=0)
    f1_cls   = f1_score(y_true, preds, average=None, zero_division=0)

    auc_roc = None
    auc_pr  = None
    if scores is not None:
        try:
            # ROC-AUC tracks TPR vs FPR trading parameters under dynamic decision thresholds
            auc_roc = roc_auc_score(y_true, scores)
            # PR-AUC (Average Precision) serves as a superior indicator under high class/feature sparsity drops
            auc_pr  = average_precision_score(y_true, scores)
        except Exception:
            pass

    return {
        "split"        : split,
        "accuracy"     : round(acc,  4),
        "precision"    : round(prec, 4),
        "recall"       : round(rec,  4),
        "f1"           : round(f1,   4),
        "mcc"          : round(mcc,  4),
        "roc_auc"      : round(auc_roc, 4) if auc_roc else None,
        "pr_auc"       : round(auc_pr,  4) if auc_pr  else None,
        # Parse localized per-class metrics splits
        "prec_fake"    : round(prec_cls[0], 4),
        "prec_real"    : round(prec_cls[1], 4),
        "rec_fake"     : round(rec_cls[0],  4),
        "rec_real"     : round(rec_cls[1],  4),
        "f1_fake"      : round(f1_cls[0],   4),
        "f1_real"      : round(f1_cls[1],   4),
    }


def print_full_report(model, model_name, train_m, test_m):
    """Generates highly readable comparative terminal logging telemetry sheets."""
    print(f"\n{'='*65}")
    print(f"  {model_name}")
    print(f"{'='*65}")

    # Display an inline train vs test metrics table tracking operational variance gap drops
    print(f"\n  {'Metric':<16}  {'TRAIN':>10}  {'TEST':>10}  {'Gap':>10}")
    print(f"  {'-'*52}")
    for key in ["accuracy", "precision", "recall", "f1", "mcc", "roc_auc", "pr_auc"]:
        tr = train_m.get(key)
        te = test_m.get(key)
        if tr is not None and te is not None:
            gap  = round(tr - te, 4)
            # Alert user if performance delta exceeds standard 5% variance threshold parameters
            flag = "  ⚠" if gap > 0.05 else ""
            print(f"  {key:<16}  {tr:>10}  {te:>10}  {gap:>+9.4f}{flag}")
        else:
            print(f"  {key:<16}  {'N/A':>10}  {'N/A':>10}")

    # Output detailed target class resolution boundaries
    print(f"\n  Per-class metrics (TEST):")
    print(f"  {'Class':<12}  {'Precision':>10}  {'Recall':>10}  {'F1':>10}")
    print(f"  {'-'*46}")
    print(f"  {'Fake (0)':<12}  {test_m['prec_fake']:>10}  {test_m['rec_fake']:>10}  {test_m['f1_fake']:>10}")
    print(f"  {'Real (1)':<12}  {test_m['prec_real']:>10}  {test_m['rec_real']:>10}  {test_m['f1_real']:>10}")

    # Ingest the standard sklearn classification report structure with support metadata
    preds = model.predict(X_test)
    print(f"\n  Classification Report (TEST):")
    report = classification_report(
        y_test, preds,
        target_names=["Fake (0)", "Real (1)"],
        digits=4
    )
    for line in report.splitlines():
        print(f"    {line}")


# =====================================================
# MAIN EVALUATION LOOP
# =====================================================

train_results = []
test_results  = []

roc_data = {}   # Dictionary array mapping parameters for final ROC curve plotting
pr_data  = {}   # Dictionary array mapping parameters for final PR curve plotting

best_model_name = None
best_f1         = 0
best_model_obj  = None

# Loop comprehensively over the registered serial model paths dict objects
for model_name, model_path in MODEL_PATHS.items():

    # Safety check to prevent structural path file missing runtime errors
    if not os.path.exists(model_path):
        print(f"\n  Skipping {model_name} — file not found: {model_path}")
        continue

    print(f"\nEvaluating: {model_name}...")
    model = pickle.load(open(model_path, "rb"))

    # Compute comprehensive evaluation metrics structures over validation sets
    train_m = compute_all_metrics(model, X_train, y_train, "TRAIN")
    test_m  = compute_all_metrics(model, X_test,  y_test,  "TEST")

    train_m["model"] = model_name
    test_m["model"]  = model_name

    train_results.append(train_m)
    test_results.append(test_m)

    print_full_report(model, model_name, train_m, test_m)

    # =====================================================
    # CONFUSION MATRIX PLOT (Unified Path Alignment Fix)
    # =====================================================
    preds = model.predict(X_test)
    cm    = confusion_matrix(y_test, preds)
    fig, ax = plt.subplots(figsize=(5, 4))
    disp = ConfusionMatrixDisplay(
        confusion_matrix=cm,
        display_labels=["Fake", "Real"]
    )
    # Draw native non-colorbar blue heatmaps for clean publication styling
    disp.plot(ax=ax, colorbar=False, cmap="Blues")
    ax.set_title(f"{model_name}\nConfusion Matrix (Test set)", fontsize=10)
    plt.tight_layout()
    safe_name = model_name.lower().replace(" ", "_")
    # Save using short '_cm.png' schema matching train_models.py
    plt.savefig(f"results/{safe_name}_cm.png", dpi=150)
    plt.close()

    # Store individual models curve array thresholds data if decision functions exist
    scores = get_scores(model, X_test)
    if scores is not None:
        fpr, tpr, _ = roc_curve(y_test, scores)
        prec_c, rec_c, _ = precision_recall_curve(y_test, scores)
        roc_data[model_name] = (fpr, tpr, test_m["roc_auc"])
        pr_data[model_name]  = (rec_c, prec_c, test_m["pr_auc"])

    # Log champion validation attributes
    if test_m["f1"] > best_f1:
        best_f1         = test_m["f1"]
        best_model_name = model_name
        best_model_obj  = model


# =====================================================
# BUILD COMBINED RESULTS TABLE
# =====================================================

# Structural format renaming logic converting raw lists into a master evaluation overview sheet
train_df = pd.DataFrame(train_results).rename(
    columns=lambda c: f"train_{c}" if c not in ["model", "split"] else c
)
test_df = pd.DataFrame(test_results).rename(
    columns=lambda c: f"test_{c}" if c not in ["model", "split"] else c
)

# Merge datasets cleanly using an inner link on model text strings
combined = pd.merge(
    train_df.drop(columns="split"),
    test_df.drop(columns="split"),
    on="model"
)

# Populate performance gap variance indicators
for metric in ["accuracy", "precision", "recall", "f1", "mcc"]:
    combined[f"gap_{metric}"] = (
        combined[f"train_{metric}"] - combined[f"test_{metric}"]
    ).round(4)

combined = combined.sort_values("test_f1", ascending=False).reset_index(drop=True)

# Reorder feature structures columns cleanly to map academic presentation formatting specs
col_order = (
    ["model"]
    + [f"train_{m}" for m in ["accuracy","precision","recall","f1","mcc","roc_auc","pr_auc"]]
    + [f"test_{m}"  for m in ["accuracy","precision","recall","f1","mcc","roc_auc","pr_auc",
                               "prec_fake","prec_real","rec_fake","rec_real","f1_fake","f1_real"]]
    + [f"gap_{m}"   for m in ["accuracy","precision","recall","f1","mcc"]]
)
combined = combined[[c for c in col_order if c in combined.columns]]

combined.to_csv("results/final_model_comparison.csv", index=False)

print("\n\n" + "="*65)
print("  FINAL LEADERBOARD (sorted by Test F1)")
print("="*65)

# Isolate priority presentation metrics for console printing
display_cols = ["model", "train_f1", "test_f1", "test_accuracy",
                "test_roc_auc", "test_pr_auc", "test_mcc",
                "gap_f1", "test_f1_fake", "test_f1_real"]
display_cols = [c for c in display_cols if c in combined.columns]
print(combined[display_cols].to_string(index=False))

print(f"\n  Best model : {best_model_name}")
print(f"  Test F1    : {best_f1:.4f}")
print("\nSaved: results/final_model_comparison.csv")


# =====================================================
# PLOT — COMBINED ROC CURVES (all models)
# =====================================================

print("\nPlotting combined ROC curves...")

# Extract a discrete palette space mapping unique line colors across architectures
cmap   = matplotlib.colormaps["tab10"]
colors = [cmap(i / len(roc_data)) for i in range(len(roc_data))]

fig, ax = plt.subplots(figsize=(8, 7))
# Draw a baseline standard random guess diagonal line at AUC=0.50
ax.plot([0, 1], [0, 1], "k--", linewidth=1, label="Random (AUC=0.50)")

# Loop line plots to graph classifier threshold limits performance
for (name, (fpr, tpr, auc)), color in zip(roc_data.items(), colors):
    label = f"{name}  (AUC={auc:.4f})" if auc else name
    ax.plot(fpr, tpr, linewidth=1.8, label=label, color=color)

ax.set_xlabel("False Positive Rate", fontsize=12)
ax.set_ylabel("True Positive Rate",  fontsize=12)
ax.set_title("ROC Curves — All Models (Test Set)", fontsize=13)
ax.legend(fontsize=8, loc="lower right")
ax.grid(linestyle="--", alpha=0.3)
plt.tight_layout()
plt.savefig("results/roc_curves_all_models.png", dpi=150)
plt.close()
print("Saved: results/roc_curves_all_models.png")


# =====================================================
# PLOT — COMBINED PRECISION-RECALL CURVES
# =====================================================

print("Plotting combined PR curves...")

fig, ax = plt.subplots(figsize=(8, 7))

# Loop line plots to graph multi-model Precision-Recall threshold variations
for (name, (rec_c, prec_c, ap)), color in zip(pr_data.items(), colors):
    label = f"{name}  (AP={ap:.4f})" if ap else name
    ax.plot(rec_c, prec_c, linewidth=1.8, label=label, color=color)

ax.set_xlabel("Recall",    fontsize=12)
ax.set_ylabel("Precision", fontsize=12)
ax.set_title("Precision-Recall Curves — All Models (Test Set)", fontsize=13)
ax.legend(fontsize=8, loc="lower left")
ax.grid(linestyle="--", alpha=0.3)
plt.tight_layout()
plt.savefig("results/pr_curves_all_models.png", dpi=150)
plt.close()
print("Saved: results/pr_curves_all_models.png")


# =====================================================
# PLOT — TRAIN vs TEST METRICS (4-panel)
# =====================================================

print("Plotting train vs test comparison...")

model_names = combined["model"].tolist()
x = np.arange(len(model_names))
w = 0.35
metrics_to_plot = [
    ("f1",       "F1 Score"),
    ("accuracy", "Accuracy"),
    ("roc_auc",  "ROC-AUC"),
    ("mcc",      "Matthews Correlation Coefficient"),
]

# Generate a 2x2 multi-panel layout canvas charting performance drops across matrices
fig, axes = plt.subplots(2, 2, figsize=(15, 10))

for ax, (metric, title) in zip(axes.flat, metrics_to_plot):
    tr_col = f"train_{metric}"
    te_col = f"test_{metric}"

    if tr_col not in combined.columns or te_col not in combined.columns:
        ax.set_visible(False)
        continue

    tr_vals = combined[tr_col].fillna(0).tolist()
    te_vals = combined[te_col].fillna(0).tolist()

    # Place Train vs Test metric columns directly adjacent for instant gap checking
    b1 = ax.bar(x - w/2, tr_vals, w, label="Train", color="#185FA5", alpha=0.85)
    b2 = ax.bar(x + w/2, te_vals, w, label="Test",  color="#E24B4A", alpha=0.85)

    ax.set_title(title, fontsize=12)
    ax.set_xticks(x)
    ax.set_xticklabels(model_names, rotation=30, ha="right", fontsize=8)
    floor = max(0, min(min(tr_vals), min(te_vals)) * 0.95)
    ax.set_ylim(floor, 1.04)
    ax.legend(fontsize=9)
    ax.grid(axis="y", linestyle="--", alpha=0.3)

    # Annotate bar segments with exact 3-digit score floats
    for bar in b1:
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.003,
                f"{bar.get_height():.3f}", ha="center", va="bottom", fontsize=7)
    for bar in b2:
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.003,
                f"{bar.get_height():.3f}", ha="center", va="bottom", fontsize=7)

plt.suptitle("Train vs Test Metrics — All Models", fontsize=14, y=1.01)
plt.tight_layout()
plt.savefig("results/train_vs_test_all_models.png", dpi=150, bbox_inches="tight")
plt.close()
print("Saved: results/train_vs_test_all_models.png")


# =====================================================
# PLOT — OVERFITTING GAP HEATMAP
# =====================================================

print("Plotting overfitting gap heatmap...")

gap_cols = ["gap_accuracy", "gap_precision", "gap_recall", "gap_f1", "gap_mcc"]
gap_cols = [c for c in gap_cols if c in combined.columns]
gap_df   = combined.set_index("model")[gap_cols].rename(
    columns=lambda c: c.replace("gap_", "").title()
)

fig, ax = plt.subplots(figsize=(8, max(4, len(model_names) * 0.65 + 1.5)))
# Draw a continuous diverging matrix plot tracking generalization risk deltas
sns.heatmap(
    gap_df,
    annot=True, fmt=".4f",
    cmap="RdYlGn_r", # Red markers isolate models presenting severe overfit conditions
    center=0, vmin=-0.02, vmax=0.15,
    linewidths=0.5, ax=ax
)
ax.set_title(
    "Train − Test Gap per Model\n(Red = larger overfit  |  Green = consistent)",
    fontsize=11
)
ax.set_xlabel("")
plt.tight_layout()
plt.savefig("results/overfitting_gap_heatmap.png", dpi=150)
plt.close()
print("Saved: results/overfitting_gap_heatmap.png")


# =====================================================
# PLOT — PER-CLASS F1 COMPARISON
# =====================================================

print("Plotting per-class F1...")

fig, ax = plt.subplots(figsize=(10, 5))
x = np.arange(len(model_names))
w = 0.35

fake_f1 = combined["test_f1_fake"].tolist()
real_f1 = combined["test_f1_real"].tolist()

# Plot comparative per-class columns to explicitly check system label balance neutrality
b1 = ax.bar(x - w/2, fake_f1, w, label="Fake (0)", color="#E24B4A", alpha=0.85)
b2 = ax.bar(x + w/2, real_f1, w, label="Real (1)", color="#185FA5", alpha=0.85)

ax.set_title("Per-Class F1 Score — Test Set", fontsize=13)
ax.set_xticks(x)
ax.set_xticklabels(model_names, rotation=25, ha="right", fontsize=9)
ax.set_ylim(min(min(fake_f1), min(real_f1)) * 0.95, 1.02)
ax.legend(fontsize=10)
ax.grid(axis="y", linestyle="--", alpha=0.3)

for bar in b1:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.002,
            f"{bar.get_height():.3f}", ha="center", va="bottom", fontsize=8)
for bar in b2:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.002,
            f"{bar.get_height():.3f}", ha="center", va="bottom", fontsize=8)

plt.tight_layout()
plt.savefig("results/per_class_f1.png", dpi=150)
plt.close()
print("Saved: results/per_class_f1.png")


# =====================================================
# PLOT — METRICS RADAR / SPIDER CHART (best model)
# =====================================================

print(f"Plotting radar chart for best model ({best_model_name})...")

best_row   = combined[combined["model"] == best_model_name].iloc[0]
radar_metrics = ["test_accuracy", "test_precision", "test_recall",
                 "test_f1", "test_roc_auc"]
radar_labels  = ["Accuracy", "Precision", "Recall", "F1", "ROC-AUC"]
radar_vals    = [best_row[m] for m in radar_metrics]

# Close the radar polygon geometry cleanly to avoid broken endpoint angles strings
angles = np.linspace(0, 2 * np.pi, len(radar_labels), endpoint=False).tolist()
angles += angles[:1]
radar_vals_c = radar_vals + radar_vals[:1]

fig, ax = plt.subplots(figsize=(6, 6), subplot_kw=dict(polar=True))
# Chart the multi-metric performance footprint in polar coordinates
ax.plot(angles, radar_vals_c, "o-", linewidth=2, color="#185FA5")
ax.fill(angles, radar_vals_c, alpha=0.25, color="#185FA5")
ax.set_xticks(angles[:-1])
ax.set_xticklabels(radar_labels, fontsize=11)
ax.set_ylim(0, 1)
ax.set_yticks([0.2, 0.4, 0.6, 0.8, 1.0])
ax.set_yticklabels(["0.2", "0.4", "0.6", "0.8", "1.0"], fontsize=8)
ax.set_title(f"Best Model: {best_model_name}\n(Test Set)", fontsize=12, pad=20)
plt.tight_layout()
plt.savefig("results/best_model_radar.png", dpi=150)
plt.close()
print("Saved: results/best_model_radar.png")


# =====================================================
# FINAL SUMMARY
# =====================================================

print("\n" + "="*65)
print("  EVALUATION COMPLETE")
print("="*65)
print(f"\n  Best model : {best_model_name}")
print(f"  Test F1    : {best_f1:.4f}")

# Extract and print out final system benchmarks to verify production execution integrity
best_row = combined[combined["model"] == best_model_name].iloc[0]
for metric in ["test_accuracy", "test_precision", "test_recall",
               "test_roc_auc", "test_pr_auc", "test_mcc"]:
    if metric in combined.columns:
        print(f"  {metric:<22}: {best_row[metric]}")

print("\nAll results saved to results/")
print("\nPlots:")
for f in [
    "roc_curves_all_models", "pr_curves_all_models",
    "train_vs_test_all_models", "overfitting_gap_heatmap",
    "per_class_f1", "best_model_radar",
]:
    print(f"   results/{f}.png")
print("   results/<model>_cm.png  (one per model)")
print("   results/final_model_comparison.csv")