# topic_modeling.py
import pickle
import numpy as np
import pandas as pd
import matplotlib
# Force matplotlib to use the non-interactive 'Agg' backend 
# to ensure server-side PNG rendering works seamlessly without a display server
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from sklearn.decomposition import LatentDirichletAllocation
from sklearn.feature_extraction.text import CountVectorizer

import os
# Establish the target results directory infrastructure if not already present
os.makedirs("results", exist_ok=True)


# =====================================================
# LOAD DATA
# =====================================================

print("Loading data...")

# Ingest the preprocessed text data corpus generated by preprocess.py
df = pd.read_csv("data/processed/cleaned_news.csv")
# Coerce the textual tokens column to standard string types and handle nulls safely
df["content"] = df["content"].fillna("").astype(str)

# Ensure zero empty strings exist post-ingestion to prevent sparse matrix mathematical errors
df = df[df["content"].str.strip().str.len() > 0].reset_index(drop=True)

print(f"Total articles : {len(df):,}")
print(f"Label distribution:")
# Display the balanced ground-truth distribution (0 = Fake / 1 = Real) 
print(df["label"].value_counts().rename({0: "Fake", 1: "Real"}).to_string())


# =====================================================
# COUNT VECTORIZER
# Use CountVectorizer (not TF-IDF) — LDA expects raw
# term counts, not weighted scores.
# Slightly stricter filtering than TF-IDF to keep
# topics cleaner.
# =====================================================

print("\nVectorizing with CountVectorizer...")

# LDA operates on a generative probabilistic framework (Dirichlet multinomial allocation)
# which models discrete integer word counts rather than non-integer TF-IDF weights.
vectorizer = CountVectorizer(
    max_features=8000,   # Constrain vocabulary vocabulary features to eliminate low-signal noise unigrams
    min_df=10,           # Exclude extremely rare words appearing in fewer than 10 documents
    max_df=0.85,         # Drop ultra-frequent tokens appearing across more than 85% of records
    ngram_range=(1, 1)   # Enforce strict unigram mapping, which yields maximum semantic stability in LDA
)

# Fit the bag-of-words document-term matrix structure
X = vectorizer.fit_transform(df["content"])
feature_names = vectorizer.get_feature_names_out()

print(f"Vocabulary size : {len(feature_names):,}")
print(f"Matrix shape    : {X.shape}")


# =====================================================
# HELPER — PRINT AND RETURN TOP WORDS PER TOPIC
# =====================================================

def get_top_words(model, feature_names, n_top=15):
    """
    Extracts the highest-weighted semantic tokens from each latent topic array.
    Sorts top parameters based on pseudo-probabilistic word weight assignments.
    """
    topics = {}
    for idx, topic in enumerate(model.components_):
        # Obtain indices of words sorted in ascending order and slice the top terms in reverse
        top_idx   = topic.argsort()[:-n_top - 1:-1]
        top_words = [feature_names[i] for i in top_idx]
        topics[idx] = top_words
    return topics


# =====================================================
# FIND BEST N_COMPONENTS USING PERPLEXITY
# Perplexity measures how well the model fits unseen
# data — lower is better. Run n=3..10 and pick the
# elbow point.
# =====================================================

print("\nSearching for best number of topics (n=3 to 10)...")

N_RANGE      = range(3, 11)
perplexities = {}

# Hyperparameter search phase to identify optimal generative semantic distributions
for n in N_RANGE:
    lda = LatentDirichletAllocation(
        n_components=n,
        max_iter=10,           # Lower loop constraints to maximize exploration speed during grid searches
        learning_method="online", # Online variational Bayes update logic scales better over extensive corpora
        random_state=42,       # Fix seed variables to guarantee identical distribution boundaries
        n_jobs=-1              # Thread processing jobs across all available CPU cores
    )
    lda.fit(X)
    # Perplexity quantifies model uncertainty; lower values indicate a superior statistical fit
    perp = lda.perplexity(X)
    perplexities[n] = perp
    print(f"  n={n}  perplexity={perp:,.1f}")

# Extract the value minimizing perplexity bounds
best_n    = min(perplexities, key=perplexities.get)
print(f"\nBest n by perplexity: n={best_n}  ({perplexities[best_n]:,.1f})")

# --- plot perplexity ---
fig, ax = plt.subplots(figsize=(8, 4))
ns   = list(perplexities.keys())
vals = list(perplexities.values())
ax.plot(ns, vals, marker="o", linewidth=2, color="#185FA5")
ax.set_xlabel("Number of topics (n)")
ax.set_ylabel("Perplexity (lower = better)")
ax.set_title("LDA Perplexity by Number of Topics")
ax.set_xticks(ns)
ax.grid(axis="y", linestyle="--", alpha=0.4)
plt.tight_layout()
plt.savefig("results/lda_perplexity.png", dpi=150)
plt.close()
print("Saved: results/lda_perplexity.png")


# =====================================================
# FINAL LDA — train with more iterations on best n
# Also always train n=5 for interpretability comparison
# =====================================================

print(f"\nTraining final LDA (n={best_n}, max_iter=30)...")

# Execute fully optimized training loop over the calculated best target components boundary
lda_best = LatentDirichletAllocation(
    n_components=best_n,
    max_iter=30,               # Higher loop convergence ceilings to lock stable topic states
    learning_method="online",
    learning_offset=50.0,      # Downweights early iterations to reduce local minima traps
    random_state=42,
    n_jobs=-1
)
lda_best.fit(X)

print(f"Final perplexity: {lda_best.perplexity(X):,.1f}")

# Train the fixed n=5 model explicitly requested for macro-level semantic report interpretability
print("\nTraining LDA n=5 (fixed, for report)...")
lda_5 = LatentDirichletAllocation(
    n_components=5,
    max_iter=30,
    learning_method="online",
    learning_offset=50.0,
    random_state=42,
    n_jobs=-1
)
lda_5.fit(X)
print(f"n=5 perplexity: {lda_5.perplexity(X):,.1f}")


# =====================================================
# PRINT TOPICS — best model and n=5
# =====================================================

print(f"\n{'='*60}")
print(f"TOPICS — best model (n={best_n})")
print(f"{'='*60}")

# Map and review the localized vocabulary fields for the optimized mathematical model
topics_best = get_top_words(lda_best, feature_names, n_top=15)
for idx, words in topics_best.items():
    print(f"\nTopic {idx:2d}: {', '.join(words)}")

print(f"\n{'='*60}")
print("TOPICS — n=5 model")
print(f"{'='*60}")

# Map and review the localized vocabulary fields for the fixed evaluation layout
topics_5 = get_top_words(lda_5, feature_names, n_top=15)
for idx, words in topics_5.items():
    print(f"\nTopic {idx:2d}: {', '.join(words)}")


# =====================================================
# SAVE TOPICS TO CSV
# =====================================================

rows = []
# Restructure key array groupings into dictionary data frames for storage
for model_label, topics in [("best", topics_best), ("n5", topics_5)]:
    for idx, words in topics.items():
        rows.append({
            "model"  : model_label,
            "topic"  : idx,
            "words"  : ", ".join(words)
        })

pd.DataFrame(rows).to_csv("results/lda_topics.csv", index=False)
print("\nSaved: results/lda_topics.csv")


# =====================================================
# TOPIC WORD WEIGHT BARCHARTS  (n=5 model — cleaner)
# One subplot per topic, top 10 words by weight
# =====================================================

print("\nPlotting topic word weights (n=5)...")

N_DISPLAY = 10
fig, axes = plt.subplots(1, 5, figsize=(20, 5), sharey=False)
cmap = matplotlib.colormaps["tab10"]

# Loop over subplots to generate normalized term weights per topic segment
for idx, ax in enumerate(axes):
    topic     = lda_5.components_[idx]
    top_idx   = topic.argsort()[:-N_DISPLAY - 1:-1]
    top_words = [feature_names[i] for i in top_idx]
    top_vals  = topic[top_idx]
    top_vals  = top_vals / top_vals.sum()        # Transform token counts into true probability ratios

    color = cmap(idx / 5)
    ax.barh(range(N_DISPLAY), top_vals[::-1], color=color, alpha=0.85)
    ax.set_yticks(range(N_DISPLAY))
    ax.set_yticklabels(top_words[::-1], fontsize=10)
    ax.set_title(f"Topic {idx}", fontsize=12, fontweight="normal")
    ax.set_xlabel("Weight", fontsize=9)
    ax.invert_yaxis()

plt.suptitle("LDA Topic Word Weights (n=5)", fontsize=14, y=1.02)
plt.tight_layout()
plt.savefig("results/lda_topic_words.png", dpi=150, bbox_inches="tight")
plt.close()
print("Saved: results/lda_topic_words.png")


# =====================================================
# TOPIC DISTRIBUTION — FAKE vs REAL
# Transform the full corpus and compare topic mixtures
# between fake and real articles
# =====================================================

print("\nAnalyzing topic distribution by label (fake vs real)...")

# Project document count matrices directly onto the newly established topic model coordinates space
doc_topics = lda_5.transform(X)   # matrix dimensions shape: (n_documents, 5_topics)
# Assign a discrete category mapping based on the highest probability component weight index
df["dominant_topic"] = doc_topics.argmax(axis=1)

# Group rows based on target classifications (Fake = 0 vs Real = 1)
fake_docs  = doc_topics[df["label"] == 0]
real_docs  = doc_topics[df["label"] == 1]

# Extract mean column vectors representing structural topic weights across class distributions
fake_avg = fake_docs.mean(axis=0)
real_avg = real_docs.mean(axis=0)

print("\nAverage topic weight — Fake articles:")
for i, w in enumerate(fake_avg):
    print(f"  Topic {i}: {w:.4f}  ({', '.join(topics_5[i][:5])})")

print("\nAverage topic weight — Real articles:")
for i, w in enumerate(real_avg):
    print(f"  Topic {i}: {w:.4f}  ({', '.join(topics_5[i][:5])})")

# --- grouped bar chart ---
x     = np.arange(5)
width = 0.35

fig, ax = plt.subplots(figsize=(10, 5))
# Generate adjacent comparative bars tracking average topic density
bars1 = ax.bar(x - width/2, fake_avg, width, label="Fake", color="#E24B4A", alpha=0.85)
bars2 = ax.bar(x + width/2, real_avg, width, label="Real", color="#185FA5", alpha=0.85)

ax.set_xlabel("Topic")
ax.set_ylabel("Average topic weight")
ax.set_title("Average Topic Distribution — Fake vs Real Articles")
ax.set_xticks(x)
ax.set_xticklabels([f"Topic {i}" for i in range(5)])
ax.legend()
ax.grid(axis="y", linestyle="--", alpha=0.3)

# Add explicit text labels directly over visual assets tracking probability floats
for bar in bars1:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.002,
            f"{bar.get_height():.3f}", ha="center", va="bottom", fontsize=8)
for bar in bars2:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.002,
            f"{bar.get_height():.3f}", ha="center", va="bottom", fontsize=8)

plt.tight_layout()
plt.savefig("results/lda_fake_vs_real_topics.png", dpi=150)
plt.close()
print("Saved: results/lda_fake_vs_real_topics.png")


# =====================================================
# DOMINANT TOPIC DISTRIBUTION (stacked bar)
# =====================================================

print("\nPlotting dominant topic distribution...")

# Calculate dynamic aggregate frequency tables for the highest-weighted topic codes per row
fake_dom = df[df["label"] == 0]["dominant_topic"].value_counts().sort_index()
real_dom = df[df["label"] == 1]["dominant_topic"].value_counts().sort_index()

# Enforce full index mapping arrays to ensure zero-count bins prevent plotting offset runtime anomalies
idx_all  = list(range(5))
fake_dom = fake_dom.reindex(idx_all, fill_value=0)
real_dom = real_dom.reindex(idx_all, fill_value=0)

# Rescale dynamic frequency integer columns into percentage proportions
fake_pct = fake_dom / fake_dom.sum()
real_pct = real_dom / real_dom.sum()

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
colors    = [matplotlib.colormaps["tab10"](i / 5) for i in range(5)]

# Visual Plot 1: Proportional dominant themes for Fake articles
axes[0].bar(idx_all, fake_pct.values, color=colors, edgecolor="white")
axes[0].set_title("Fake articles — dominant topic")
axes[0].set_xlabel("Topic")
axes[0].set_ylabel("Proportion")
axes[0].set_xticks(idx_all)

# Visual Plot 2: Proportional dominant themes for Real articles
axes[1].bar(idx_all, real_pct.values, color=colors, edgecolor="white")
axes[1].set_title("Real articles — dominant topic")
axes[1].set_xlabel("Topic")
axes[1].set_ylabel("Proportion")
axes[1].set_xticks(idx_all)

plt.suptitle("Dominant Topic Distribution by Label", fontsize=13)
plt.tight_layout()
plt.savefig("results/lda_dominant_topic_distribution.png", dpi=150)
plt.close()
print("Saved: results/lda_dominant_topic_distribution.png")


# =====================================================
# SAVE ARTIFACTS
# =====================================================

# Serialize optimized LDA components objects for downstream deployment interfaces
pickle.dump(lda_best, open("models/lda_best.pkl",  "wb"))
pickle.dump(lda_5,    open("models/lda_n5.pkl",    "wb"))
pickle.dump(vectorizer, open("models/lda_count_vectorizer.pkl", "wb"))

# Dump core label maps to guide the dynamic downsampling filter within balance_topics.py
df[["label", "dominant_topic"]].to_csv(
    "results/document_topic_assignments.csv", index=False
)

print("\n✅ Topic modeling complete")
print(f"   Best n (perplexity): {best_n}")
print(f"   n=5 perplexity     : {lda_5.perplexity(X):,.1f}")
print("\nModels saved:")
print("   models/lda_best.pkl")
print("   models/lda_n5.pkl")
print("   models/lda_count_vectorizer.pkl")
print("\nPlots saved:")
for f in ["lda_perplexity", "lda_topic_words",
          "lda_fake_vs_real_topics", "lda_dominant_topic_distribution"]:
    print(f"   results/{f}.png")
print("   results/lda_topics.csv")
print("   results/document_topic_assignments.csv")