# train_models.py

import pickle
import numpy as np
import pandas as pd
import matplotlib
# Force matplotlib to use the non-interactive 'Agg' backend 
# to ensure server-side PNG rendering works seamlessly without a display server
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import GridSearchCV, StratifiedKFold, cross_validate
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix,
    classification_report
)

import os
# Establish the localized directory architecture if not already present
os.makedirs("models",  exist_ok=True)
os.makedirs("results", exist_ok=True)


# =====================================================
# LOAD DATA
# =====================================================

print("Loading data...")

# Ingest the high-integrity sparse data matrices generated by balance_topics.py
X_train = pickle.load(open("data/processed/X_train.pkl", "rb"))
X_test  = pickle.load(open("data/processed/X_test.pkl",  "rb"))
y_train = pickle.load(open("data/processed/y_train.pkl", "rb"))
y_test  = pickle.load(open("data/processed/y_test.pkl",  "rb"))

print(f"Train : {X_train.shape[0]:,} samples  |  Test : {X_test.shape[0]:,} samples")
print(f"Train label dist: {dict(pd.Series(y_train).value_counts().rename({0:'Fake',1:'Real'}))}")
print(f"Test  label dist: {dict(pd.Series(y_test).value_counts().rename({0:'Fake',1:'Real'}))}")


# =====================================================
# HELPER — COMPUTE FULL METRIC SET FOR ONE SPLIT
# =====================================================

def compute_metrics(model, X, y_true, split_name):
    """
    Returns a dict with all metrics for a given split.
    Handles both predict_proba and decision_function models.
    """
    # Generate discrete binary category predictions
    preds = model.predict(X)

    # Compute foundational supervised classification performance indicators
    acc  = accuracy_score(y_true, preds)
    prec = precision_score(y_true, preds, zero_division=0)
    rec  = recall_score(y_true, preds, zero_division=0)
    f1   = f1_score(y_true, preds, zero_division=0)

    # Safe evaluation of ROC-AUC score to handle architectural discrepancies natively
    try:
        # Logistic Regression and Naive Bayes provide class probability arrays
        if hasattr(model, "predict_proba"):
            scores = model.predict_proba(X)[:, 1]
        # LinearSVC provides a continuous raw distance score from the hyper-plane
        else:
            scores = model.decision_function(X)
        auc = roc_auc_score(y_true, scores)
    except Exception:
        auc = None

    return {
        "split"    : split_name,
        "accuracy" : round(acc,  4),
        "precision": round(prec, 4),
        "recall"   : round(rec,  4),
        "f1"       : round(f1,   4),
        "roc_auc"  : round(auc,  4) if auc is not None else None
    }


def print_metrics(metrics, model_name):
    """Prints out parsed metric values cleanly to the system standard output."""
    print(f"\n  {'Metric':<12}  {metrics['split']}")
    print(f"  {'-'*30}")
    for key in ["accuracy", "precision", "recall", "f1", "roc_auc"]:
        val = metrics[key]
        print(f"  {key:<12}  {val if val is not None else 'N/A'}")


def evaluate_both_splits(model, model_name):
    """
    Evaluates on TRAIN and TEST, prints both, prints
    classification report for test, and returns both dicts.
    """
    train_m = compute_metrics(model, X_train, y_train, "TRAIN")
    test_m  = compute_metrics(model, X_test,  y_test,  "TEST")

    print(f"\n{'='*60}")
    print(f"  {model_name}")
    print(f"{'='*60}")

    # Parse and display a side-by-side performance validation table
    print(f"\n  {'Metric':<12}  {'TRAIN':>10}  {'TEST':>10}  {'Overfit?':>10}")
    print(f"  {'-'*50}")
    for key in ["accuracy", "precision", "recall", "f1", "roc_auc"]:
        tr  = train_m[key]
        te  = test_m[key]
        if tr is not None and te is not None:
            # Track generalization variance drop metrics
            gap  = round(tr - te, 4)
            flag = " ⚠ overfit" if gap > 0.05 else ""
            print(f"  {key:<12}  {tr:>10}  {te:>10}  {gap:>+8.4f}{flag}")
        else:
            print(f"  {key:<12}  {'N/A':>10}  {'N/A':>10}")

    print(f"\n  Classification Report (TEST):")
    preds = model.predict(X_test)
    # Generate complete per-class breakdowns including target support counts
    report = classification_report(
        y_test, preds,
        target_names=["Fake (0)", "Real (1)"],
        digits=4
    )
    for line in report.splitlines():
        print(f"    {line}")

    return train_m, test_m


# =====================================================
# SAVE CONFUSION MATRIX PLOT
# =====================================================

def save_confusion_matrix(model, model_name):
    """Generates and saves scaled Seaborn heatmaps for the confusion matrix."""
    preds = model.predict(X_test)
    cm    = confusion_matrix(y_test, preds)

    fig, ax = plt.subplots(figsize=(5, 4))
    sns.heatmap(
        cm, annot=True, fmt="d", cmap="Blues", ax=ax,
        xticklabels=["Fake", "Real"],
        yticklabels=["Fake", "Real"]
    )
    ax.set_title(f"{model_name}\nConfusion Matrix (Test)")
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual")
    plt.tight_layout()

    # Unified filename string parsing logic to map pipeline conventions
    filename = "results/" + model_name.lower().replace(" ", "_") + "_cm.png"
    plt.savefig(filename, dpi=150)
    plt.close()


# =====================================================
# CROSS-VALIDATION HELPER
# =====================================================

def cross_val_summary(model, model_name, cv=5):
    """
    Runs stratified 5-fold CV and prints mean ± std for
    accuracy, precision, recall, f1.
    """
    # Stratified folds protect class balances across every cross-validation slice
    skf = StratifiedKFold(n_splits=cv, shuffle=True, random_state=42)
    scoring = ["accuracy", "precision", "recall", "f1"]

    cv_results = cross_validate(
        model, X_train, y_train,
        cv=skf,
        scoring=scoring,
        n_jobs=-1,          # Distribute parallel folds processing jobs across CPU resources
        return_train_score=True
    )

    print(f"\n  {cv}-Fold Cross-Validation on TRAIN:")
    print(f"  {'Metric':<12}  {'Train mean':>12}  {'Train std':>10}  {'Val mean':>10}  {'Val std':>10}")
    print(f"  {'-'*62}")
    # Compute statistical standard deviation boundaries across training loops
    for metric in scoring:
        tr_mean = np.mean(cv_results[f"train_{metric}"])
        tr_std  = np.std( cv_results[f"train_{metric}"])
        v_mean  = np.mean(cv_results[f"test_{metric}"])
        v_std   = np.std( cv_results[f"test_{metric}"])
        print(f"  {metric:<12}  {tr_mean:>12.4f}  {tr_std:>10.4f}  {v_mean:>10.4f}  {v_std:>10.4f}")


# =====================================================
# COLLECT ALL RESULTS
# =====================================================

all_train_results = []
all_test_results  = []

best_model      = None
best_f1_test    = 0
best_model_name = ""


# =====================================================
# BASELINE MODELS
# =====================================================

print("\n" + "#"*60)
print("  BASELINE MODELS")
print("#"*60)

# Dictionary initialization tracking core un-tuned algorithmic frameworks
baseline_models = {
    "Logistic Regression": LogisticRegression(
        max_iter=1000, random_state=42
    ),
    "Naive Bayes": MultinomialNB(),
    "SVM": LinearSVC(
        random_state=42, max_iter=2000
    ),
    "Random Forest": RandomForestClassifier(
        n_estimators=200, random_state=42, n_jobs=-1
    )
}

# Run execution tracking loop for all basic architectures
for model_name, model in baseline_models.items():
    print(f"\nTraining {model_name}...")
    model.fit(X_train, y_train)
    # Serialize baseline models to disk
    fname = model_name.lower().replace(" ", "_")
    pickle.dump(model, open(f"models/{fname}.pkl", "wb"))
    # Compute 5-fold cross-validation metrics
    cross_val_summary(model, model_name)
    # Evaluate train vs test generalization splits
    train_m, test_m = evaluate_both_splits(model, model_name)
    train_m["model"] = model_name
    test_m["model"]  = model_name
    all_train_results.append(train_m)
    all_test_results.append(test_m)

    # Output individual confusion matrices
    save_confusion_matrix(model, model_name)

    # Track operational champion criteria based on Test F1 stability
    if test_m["f1"] > best_f1_test:
        best_f1_test    = test_m["f1"]
        best_model      = model
        best_model_name = model_name


# =====================================================
# TUNE LOGISTIC REGRESSION
# =====================================================

print("\n" + "#"*60)
print("  HYPERPARAMETER TUNING")
print("#"*60)

print("\nTuning Logistic Regression (GridSearchCV)...")

# Construct optimization parameter grid searching inverse regularization constants
lr_grid = GridSearchCV(
    LogisticRegression(max_iter=1000, random_state=42),
    param_grid={"C": [0.01, 0.1, 1, 10]},
    cv=5, scoring="f1", n_jobs=-1, refit=True, verbose=0
)
lr_grid.fit(X_train, y_train)
print(f"  Best params : {lr_grid.best_params_}")
print(f"  Best CV F1  : {lr_grid.best_score_:.4f}")

# Extract and serialize optimized Logistic Regression configurations
best_lr = lr_grid.best_estimator_
pickle.dump(best_lr, open("models/logistic_regression_tuned.pkl", "wb"))

train_m, test_m = evaluate_both_splits(best_lr, "Tuned Logistic Regression")
train_m["model"] = "Tuned Logistic Regression"
test_m["model"]  = "Tuned Logistic Regression"
all_train_results.append(train_m)
all_test_results.append(test_m)
save_confusion_matrix(best_lr, "Tuned Logistic Regression")

if test_m["f1"] > best_f1_test:
    best_f1_test    = test_m["f1"]
    best_model      = best_lr
    best_model_name = "Tuned Logistic Regression"


# =====================================================
# TUNE SVM
# =====================================================

print("\nTuning SVM (GridSearchCV)...")

# GridSearch optimization targeting the cost function margin penalty constraint parameters (C)
svm_grid = GridSearchCV(
    LinearSVC(random_state=42, max_iter=2000),
    param_grid={"C": [0.01, 0.1, 1, 10]},
    cv=5, scoring="f1", n_jobs=-1, refit=True, verbose=0
)
svm_grid.fit(X_train, y_train)
print(f"  Best params : {svm_grid.best_params_}")
print(f"  Best CV F1  : {svm_grid.best_score_:.4f}")

# Extract and serialize optimized Support Vector Machine objects
best_svm = svm_grid.best_estimator_
pickle.dump(best_svm, open("models/svm_tuned.pkl", "wb"))

train_m, test_m = evaluate_both_splits(best_svm, "Tuned SVM")
train_m["model"] = "Tuned SVM"
test_m["model"]  = "Tuned SVM"
all_train_results.append(train_m)
all_test_results.append(test_m)
save_confusion_matrix(best_svm, "Tuned SVM")

if test_m["f1"] > best_f1_test:
    best_f1_test    = test_m["f1"]
    best_model      = best_svm
    best_model_name = "Tuned SVM"


# =====================================================
# TUNE RANDOM FOREST
# =====================================================

print("\nTuning Random Forest (GridSearchCV)...")

# Optimization hyperparameter space mapping tree deep criteria bounds alongside estimators counts
rf_grid = GridSearchCV(
    RandomForestClassifier(random_state=42, n_jobs=-1),
    param_grid={
        "n_estimators": [100, 200],
        "max_depth"   : [10, 20, None]
    },
    cv=5, scoring="f1", n_jobs=-1, refit=True, verbose=0
)
rf_grid.fit(X_train, y_train)
print(f"  Best params : {rf_grid.best_params_}")
print(f"  Best CV F1  : {rf_grid.best_score_:.4f}")

# Extract and serialize optimized Random Forest Ensembles
best_rf = rf_grid.best_estimator_
pickle.dump(best_rf, open("models/random_forest_tuned.pkl", "wb"))

train_m, test_m = evaluate_both_splits(best_rf, "Tuned Random Forest")
train_m["model"] = "Tuned Random Forest"
test_m["model"]  = "Tuned Random Forest"
all_train_results.append(train_m)
all_test_results.append(test_m)
save_confusion_matrix(best_rf, "Tuned Random Forest")

if test_m["f1"] > best_f1_test:
    best_f1_test    = test_m["f1"]
    best_model      = best_rf
    best_model_name = "Tuned Random Forest"


# =====================================================
# SAVE BEST MODEL
# =====================================================

# Export final project champion model and match its underlying TF-IDF vectorizer configuration
pickle.dump(best_model, open("models/best_model.pkl", "wb"))
pickle.dump(
    pickle.load(open("models/tfidf_vectorizer.pkl", "rb")),
    open("models/vectorizer.pkl", "wb")
)

print(f"\n{'='*60}")
print(f"  Best model : {best_model_name}")
print(f"  Test F1    : {best_f1_test:.4f}")
print(f"{'='*60}")


# =====================================================
# COMBINED RESULTS TABLE
# =====================================================

# Parse lists of metric arrays into matching Pandas tabular evaluation dataframes
train_df = pd.DataFrame(all_train_results).rename(
    columns=lambda c: f"train_{c}" if c not in ["model", "split"] else c
)
test_df  = pd.DataFrame(all_test_results).rename(
    columns=lambda c: f"test_{c}" if c not in ["model", "split"] else c
)

# Conduct full SQL-style inner merge tracking metrics over identical architecture keys
combined = pd.merge(
    train_df.drop(columns="split"),
    test_df.drop(columns="split"),
    on="model"
)

# Calculate explicit generalization gap variance floats
for metric in ["accuracy", "precision", "recall", "f1"]:
    combined[f"gap_{metric}"] = (
        combined[f"train_{metric}"] - combined[f"test_{metric}"]
    ).round(4)

combined = combined.sort_values("test_f1", ascending=False).reset_index(drop=True)

# Re-order columns strictly to maximize human readability within final paper appendices
col_order = (
    ["model"]
    + [f"train_{m}" for m in ["accuracy","precision","recall","f1","roc_auc"]]
    + [f"test_{m}"  for m in ["accuracy","precision","recall","f1","roc_auc"]]
    + [f"gap_{m}"   for m in ["accuracy","precision","recall","f1"]]
)
combined = combined[[c for c in col_order if c in combined.columns]]

combined.to_csv("results/model_comparison_full.csv", index=False)

print("\n\nFULL MODEL COMPARISON (sorted by test F1):")
print(combined.to_string(index=False))
print("\nSaved: results/model_comparison_full.csv")


# =====================================================
# VISUALIZATION — TRAIN vs TEST F1 GROUPED BAR
# =====================================================

print("\nPlotting train vs test comparison...")

# Initialize a comprehensive 4-panel subplots grid to visualize algorithmic variance
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
metrics   = ["f1", "accuracy", "precision", "recall"]
titles    = ["F1 Score", "Accuracy", "Precision", "Recall"]

model_names = combined["model"].tolist()
x = np.arange(len(model_names))
w = 0.35

for ax, metric, title in zip(axes.flat, metrics, titles):
    train_vals = combined[f"train_{metric}"].tolist()
    test_vals  = combined[f"test_{metric}"].tolist()

    # Draw adjacent bars evaluating performance drop constraints
    b1 = ax.bar(x - w/2, train_vals, w, label="Train", color="#185FA5", alpha=0.85)
    b2 = ax.bar(x + w/2, test_vals,  w, label="Test",  color="#E24B4A", alpha=0.85)

    ax.set_title(title, fontsize=12)
    ax.set_xticks(x)
    ax.set_xticklabels(model_names, rotation=30, ha="right", fontsize=8)
    # Dynamically crop lower chart margins to maximize performance delta variations visibility
    ax.set_ylim(min(min(train_vals), min(test_vals)) * 0.95, 1.02)
    ax.legend(fontsize=9)
    ax.grid(axis="y", linestyle="--", alpha=0.3)
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f"{v:.2f}"))

    # Overlay numeric floating values directly over chart elements
    for bar in b1:
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.002,
                f"{bar.get_height():.3f}", ha="center", va="bottom", fontsize=7)
    for bar in b2:
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.002,
                f"{bar.get_height():.3f}", ha="center", va="bottom", fontsize=7)

plt.suptitle("Train vs Test Metrics — All Models", fontsize=14, y=1.01)
plt.tight_layout()
plt.savefig("results/train_vs_test_metrics.png", dpi=150, bbox_inches="tight")
plt.close()
print("Saved: results/train_vs_test_metrics.png")


# =====================================================
# VISUALIZATION — OVERFITTING GAP HEATMAP
# =====================================================

print("Plotting overfitting gap heatmap...")

gap_cols = ["gap_accuracy", "gap_precision", "gap_recall", "gap_f1"]
gap_df   = combined.set_index("model")[gap_cols].rename(
    columns=lambda c: c.replace("gap_", "").title()
)

fig, ax = plt.subplots(figsize=(8, len(model_names) * 0.7 + 1.5))
# Generate a divergent color heatmap evaluating structural variance drop deltas
sns.heatmap(
    gap_df,
    annot=True, fmt=".4f",
    cmap="RdYlGn_r",   # Red indicates higher generalization dropouts (overfitting hazards)
    center=0,
    linewidths=0.5,
    ax=ax,
    vmin=-0.01, vmax=0.15
)
ax.set_title("Train − Test Gap (Overfitting Check)\nRed = higher overfit, Green = consistent", fontsize=11)
ax.set_xlabel("")
ax.set_ylabel("")
plt.tight_layout()
plt.savefig("results/overfitting_gap_heatmap.png", dpi=150)
plt.close()
print("Saved: results/overfitting_gap_heatmap.png")


# =====================================================
# DONE
# =====================================================

print("\n✅ Training complete")
print(f"   Best model : {best_model_name}")
print(f"   Test F1    : {best_f1_test:.4f}")

print("\nModels saved : models/")
print("Results saved:")
print("   results/model_comparison_full.csv")
print("   results/train_vs_test_metrics.png")
print("   results/overfitting_gap_heatmap.png")
print("   results/<model>_cm.png  (one per model)")
print("\n📝 Next Step: Execute 'python evaluate.py' to generate advanced evaluation curve plots.")